### ISSUE TITLE
select dropdown with html5 required attribute

### ISSUE THREAD

**Issue by neobie** [designmodo/Flat-UI#196] opened 2015-08-01 08:36 UTC
If the <select> element which is using flat-ui has an attribute "required", the form submission would be failed and seems like nothing happen. This is due to <select> is having display:none style.

From the Chrome console log:
An invalid form control with name=elementName is not focusable.

What is the better alternative to solve this, other than removing the "required" attribute?

**Comment by StefanYohansson** [comment] 2015-12-17 15:11
answer by emboss in stackoverflow:

"The cause seems to be HTML 5 constraint validation - it's the require attribute. Chrome has started supporting this with it's recent versions.

Apparently it seems like this is a backward compatibility issue, but you can fix it with setting the formnovalidate attribute for your submit button.

I assume that this is actually a security feature that prevents submitting supposed user data by submitting manipulated, hidden content, this quote points in that direction:

    If one of the controls is not being rendered (e.g. it has the hidden attribute set) then user agents may report a script error.

Your inputs are of type text, so their purpose is to let users enter data, submitting their content while hidden is something that a user probably wouldn't want.

If you still want to submit hidden inputs while using client validation, I would suggest using <input type="hidden"> instead - I could imagine that there is no error on validation there because they are intended to be invisible."

http://stackoverflow.com/questions/7183692/google-chrome-cannot-submit-form-with-displaynone

**Comment by StefanYohansson** [comment] 2016-03-31 14:29
I'm closing this issue. If you want just reopen.

**Closed by StefanYohansson** 2016-03-31 14:29 UTC
Labels: question, wontfix
